# -*- coding: utf-8 -*-
"""PythonAssignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCg0FFUQDHBfivLwBgTq2kuwkcsVvk-l

#Python Assignment 1
"""

# Task 1: Largest of three numbers
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

if a >= b and a >= c:
    largest = a
elif b >= a and b >= c:
    largest = b
else:
    largest = c

print("Largest number is:", largest)

# Task 2: Even or Odd
n = int(input("Enter an integer: "))
if n % 2 == 0:
    print("Even")
else:
    print("Odd")

# Task 3: Skip numbers divisible by 7
for i in range(1, 101):
    if i % 7 == 0:
        continue
    print(i, end=" ")
print()

# Task 4: Multiplication table
n = int(input("Enter a number for its multiplication table: "))
for i in range(1, 11):
    print(f"{n} x {i} = {n * i}")

# Task 5: Right-angled triangle pattern
rows = int(input("Enter number of rows: "))
for i in range(1, rows + 1):
    for j in range(i):
        print("*", end="")
    print()

# Task 6: Incremental number pattern
rows = int(input("Enter number of rows: "))
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end="")
    print()

# Task 7: Vowel or Consonant
ch = input("Enter a single alphabet: ").strip()
if len(ch) != 1 or not ch.isalpha():
    print("Not an alphabet character.")
else:
    if ch.lower() in "aeiou":
        print("Vowel")
    else:
        print("Consonant")

# Task 8: Diamond pattern of stars (no spaces; matches sample)
n = int(input("Enter n (e.g., 5): "))
for i in range(1, n + 1):
    print("*" * (2 * i - 1))
for i in range(n - 1, 0, -1):
    print("*" * (2 * i - 1))

# Task 9: Reverse digits of a number
num = int(input("Enter an integer: "))
sign = -1 if num < 0 else 1
num = abs(num)

rev = 0
while num > 0:
    rev = rev * 10 + (num % 10)
    num //= 10

print("Reversed number:", sign * rev)

# Task 10: Numeric pyramid
n = int(input("Enter number of rows (e.g., 5): "))
for i in range(1, n + 1):
    left = "".join(str(x) for x in range(1, i + 1))
    right = "".join(str(x) for x in range(i - 1, 0, -1))
    print(left + right)

"""By,
Utkarsh Anand
"""